import type { PublicListing } from "./catalog";

export const PUBLISHED_LISTINGS: PublicListing[] = [
  {
    id: "ji-001",
    sku: "JI-001",
    name: 'CWD SE01 17.5" 2024',
    brand: "CWD",
    model: "SE01",
    year: "2024",
    seat: '17.5"',
    flap: "On file",
    tree: "On file",
    serial: "114716",
    stamps: "CWD · SE01 · 17.5 · 114716 · 24",
    condition: "Excellent",
    wear: "Even, light wear consistent with careful schooling. Billets and panels present cleanly.",
    price: 4690,
    program: "South Bay Select",
    includesCover: true,
    published: true,
    discipline: "English",
    location: "South Bay",
    serviceHistory: "Pre-owned; cover included. Founder-reviewed before publish.",
    route: "verified",
    summary:
      "Pre-owned CWD SE01 in Excellent condition. South Bay Select, offered with cover.",
    photoLabels: [
      "near-side",
      "off-side",
      "seat",
      "front",
      "rear",
      "flaps",
      "billets",
      "panels",
      "stamps",
    ],
    // Cantle nameplate is founder-private and is never rendered on Details.
  },
  {
    id: "an-014",
    sku: "AN-014",
    name: 'Antares Connexion 17.5" 2021',
    brand: "Antares",
    model: "Connexion",
    year: "2021",
    seat: '17.5"',
    flap: "2A",
    tree: "Medium",
    serial: "AN21488",
    stamps: "Antares · Connexion · 17.5 · 2A · 21",
    condition: "Very good",
    wear: "Softening at the knee rolls; panels remain even.",
    price: 3890,
    program: "Collection",
    includesCover: true,
    published: true,
    discipline: "English",
    location: "South Bay",
    serviceHistory: "Restuffed 2024.",
    route: "marketplace",
    summary: "Pre-owned Antares Connexion, English close-contact.",
    photoLabels: [
      "near-side",
      "off-side",
      "seat",
      "front",
      "rear",
      "flaps",
      "billets",
      "panels",
      "stamps",
    ],
  },
  {
    id: "bt-008",
    sku: "BT-008",
    name: 'Butet Practice 17" 2019',
    brand: "Butet",
    model: "Practice",
    year: "2019",
    seat: '17"',
    flap: "L",
    tree: "Medium-wide",
    serial: "BT19072",
    stamps: "Butet · Practice · 17 · L · 19",
    condition: "Excellent",
    wear: "Quiet seat shine; flaps still firm.",
    price: 4200,
    program: "Collection",
    includesCover: false,
    published: true,
    discipline: "English",
    location: "South Bay",
    serviceHistory: "Conditioned annually.",
    route: "marketplace",
    summary: "Pre-owned Butet Practice, English jump.",
    photoLabels: [
      "near-side",
      "off-side",
      "seat",
      "front",
      "rear",
      "flaps",
      "billets",
      "panels",
      "stamps",
    ],
  },
  {
    id: "vd-021",
    sku: "VD-021",
    name: 'Voltaire Design Palm Beach 18" 2022',
    brand: "Voltaire Design",
    model: "Palm Beach",
    year: "2022",
    seat: '18"',
    flap: "2A",
    tree: "Medium",
    serial: "VD22891",
    stamps: "Voltaire · Palm Beach · 18 · 2A · 22",
    condition: "Very good",
    wear: "Light billet stretch; no panel asymmetry noted.",
    price: 3450,
    program: "Collection",
    includesCover: true,
    published: true,
    discipline: "English",
    location: "South Bay",
    serviceHistory: "Billets checked 2025.",
    route: "marketplace",
    summary: "Pre-owned Voltaire Design Palm Beach.",
    photoLabels: [
      "near-side",
      "off-side",
      "seat",
      "front",
      "rear",
      "flaps",
      "billets",
      "panels",
      "stamps",
    ],
  },
];

export function getSeedListing(id: string) {
  return PUBLISHED_LISTINGS.find((listing) => listing.id === id);
}
